version: '2'
services:
    mysql-mentoring:
       build: mysql
       ports: 
        - "3307:3306"
       network_mode: bridge
       container_name: mysql-mentoring
       volumes:
         - /opt/data
       hostname: mysql-mentoring
       restart: unless-stopped
    tomcat-mentoring:
       build: tomcat
       ports:
         # - "8081:8080"
         - "8000:8000"
       network_mode: bridge
       container_name: tomcat-mentoring
       depends_on:
         - mysql-mentoring
       links:
         - mysql-mentoring
       volumes: 
         - /opt/data/webapp:/usr/local/tomcat/webapps
       hostname: tomcat-mentoring
       restart: unless-stopped