version: '2'
services:
    mysql-mentoring:
       build: mysql
       ports: 
        - "3307:3306"
       networks:
        - network
       container_name: mysql-mentoring
       volumes:
         - /opt/data/webapp/mentoring:/usr/local/mysql
       hostname: mysql-mentoring
       restart: unless-stopped
    tomcat-mentoring:
       build: tomcat
       ports:
         - "8080:8080"
         - "8000:8000"
       networks: 
         - network
         - account-manager_network
       external_links:
         - tomcat-account
       container_name: tomcat-mentoring
       depends_on:
         - mysql-mentoring
       links:
         - mysql-mentoring
       volumes: 
         - /opt/data/webapp/mentoring:/usr/local/tomcat/webapps
       hostname: tomcat-mentoring
       restart: unless-stopped

networks:
  network:
    driver: bridge
  account-manager_network:
    external: true
