version: '2.1'
services:
    mysql-mentoring:
       build: mysql
       ports: 
        - "${MENTORING_MYSQL_PUBLISHED_PORT:-3307}:3306"
       networks:
        - network
       container_name: mysql-mentoring
       volumes:
         - ${MENTORING_MYSQL_DIR:-/opt/data/webapp/mentoring}:/usr/local/mysql
       hostname: mysql-mentoring
       restart: unless-stopped
    tomcat-mentoring:
       build: tomcat
       ports:
         - "${MENTORING_TOMCAT_PUBLISHED_PORT:-8080}:8080"
         - "8000:8000"
       networks: 
         - network
         - account-manager_network
       external_links:
         - tomcat-account
       container_name: tomcat-mentoring
       depends_on:
         - mysql-mentoring
       links:
         - mysql-mentoring
       volumes: 
         - ${MENTORING_TOMCAT_WEBAPPS_DIR:-/opt/data/webapp/mentoring}:/usr/local/tomcat/webapps
       hostname: tomcat-mentoring
       restart: unless-stopped

networks:
  network:
    driver: bridge
  account-manager_network:
    external: true
