-- INDICATORS
CREATE TABLE `INDICATORS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `LIFE_CYCLE_STATUS` VARCHAR(100) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(50) NOT NULL,
  `PERFORMED_DATE` DATETIME NOT NULL,
  `REFERRED_MONTH` DATE NOT NULL,
  `FORM_ID` BIGINT(20) NOT NULL,
  `HEALTH_FACILITY_ID` BIGINT(20) NOT NULL,
  `TUTOR_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CODE` (`CODE`),
  KEY `FK_FORM_ID` (`FORM_ID`),
  KEY `FK_HEALTH_FACILITY_ID` (`HEALTH_FACILITY_ID`),
  KEY `FK_TUTOR_ID` (`TUTOR_ID`),
  CONSTRAINT `FK_TUTOR_ID` FOREIGN KEY (`TUTOR_ID`) REFERENCES `TUTORS` (`ID`),
  CONSTRAINT `FK_HEALTH_FACILITY_ID` FOREIGN KEY (`HEALTH_FACILITY_ID`) REFERENCES `HEALTH_FACILITIES` (`ID`),
  CONSTRAINT `FK_FORM_ID` FOREIGN KEY (`FORM_ID`) REFERENCES `FORMS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ANSWERS
ALTER TABLE ANSWERS ADD COLUMN `INDICATOR_ID` BIGINT(20);
ALTER TABLE ANSWERS ADD CONSTRAINT `FK_INDICATOR_ID` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `INDICATORS` (`ID`);
ALTER TABLE ANSWERS MODIFY COLUMN `MENTORSHIP_ID` BIGINT(20);

-- FORMS
ALTER TABLE FORMS ADD COLUMN `FORM_TYPE` VARCHAR(50) NOT NULL DEFAULT 'MENTORING';