-- CABINETS
CREATE TABLE `CABINETS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `LIFE_CYCLE_STATUS` VARCHAR(100) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- MENTORSHIPS
ALTER TABLE MENTORSHIPS ADD COLUMN `CABINET_ID` BIGINT(20);
ALTER TABLE MENTORSHIPS ADD CONSTRAINT `FK_CABINET_ID` FOREIGN KEY (`CABINET_ID`) REFERENCES `CABINETS` (`ID`);