-- FORM_TARGETS
CREATE TABLE `FORM_TARGETS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `LIFE_CYCLE_STATUS` VARCHAR(100) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `TARGET` INT(11) NOT NULL,
  `CAREER_ID` BIGINT(20) NOT NULL,
  `FORM_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_FORM_TARGETS_FORM_ID_CAREER_ID` (`FORM_ID`,`CAREER_ID`),
  KEY `FK_FORM_TARGETS_CAREER_ID` (`CAREER_ID`),
  CONSTRAINT `FK_FORM_TARGETS_FORM_ID` FOREIGN KEY (`FORM_ID`) REFERENCES `FORMS` (`ID`),
  CONSTRAINT `FK_FORM_TARGETS_CAREER_ID` FOREIGN KEY (`CAREER_ID`) REFERENCES `CARRERS` (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;