-- QUESTION_CATEGORIES
CREATE TABLE `QUESTION_CATEGORIES` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` datetime NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `LIFE_CYCLE_STATUS` VARCHAR(100) NOT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `CATEGORY` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `QUESTIONS` ADD COLUMN `QUESTION_CATEGORY_ID` bigint(20) DEFAULT NULL;
ALTER TABLE `QUESTIONS` ADD CONSTRAINT `FK_QUESTIONS_QUESTION_CATEGORY_ID` FOREIGN KEY(`QUESTION_CATEGORY_ID`) REFERENCES `QUESTION_CATEGORIES` (`ID`);
ALTER TABLE `QUESTIONS` CHANGE QUESTION_CATEGORY QUESTION_CATEGORY VARCHAR(50);