-- PARTNERS
CREATE TABLE `PARTNERS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `LIFE_CYCLE_STATUS` VARCHAR(100) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `FORMS` ADD COLUMN `PARTNER_ID` bigint(20) DEFAULT NULL;
ALTER TABLE `FORMS` ADD CONSTRAINT `FK_FORMS_PARTNER_ID` FOREIGN KEY(`PARTNER_ID`) REFERENCES `FORMS` (`ID`);

ALTER TABLE `TUTORS` ADD COLUMN `PARTNER_ID` bigint(20) DEFAULT NULL;
ALTER TABLE `TUTORS` ADD CONSTRAINT `FK_TUTORS_PARTNER_ID` FOREIGN KEY(`PARTNER_ID`) REFERENCES `TUTORS` (`ID`);

-- TUTOR_LOCATIONS
CREATE TABLE `TUTOR_LOCATIONS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `LIFE_CYCLE_STATUS` VARCHAR(100) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `TUTOR_ID` BIGINT(20) NOT NULL,
  `LOCATION_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_TUTOR_LOCATIONS_TUTOR_ID` (`TUTOR_ID`),
  KEY `FK_TUTOR_LOCATIONS_LOCATION_ID` (`LOCATION_ID`),
  CONSTRAINT `FK_TUTOR_LOCATIONS_TUTOR_ID` FOREIGN KEY (`TUTOR_ID`) REFERENCES `TUTORS` (`ID`),
  CONSTRAINT `FK_TUTOR_LOCATIONS_LOCATION_ID` FOREIGN KEY (`LOCATION_ID`) REFERENCES `HEALTH_FACILITIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;