-- TUTOR
ALTER TABLE TUTORS ADD COLUMN `EMAIL` VARCHAR(50) NOT NULL DEFAULT 'NA';
ALTER TABLE TUTORS ADD COLUMN `IS_USER` bit(1) NOT NULL;

--TUTOREDS
ALTER TABLE TUTOREDS ADD COLUMN `EMAIL` VARCHAR(50) NOT NULL DEFAULT 'NA';
